# Generated by Django 2.0.7 on 2018-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='picture',
            field=models.ImageField(null=True, upload_to='../frontend/static/media'),
        ),
    ]
