# Generated by Django 2.0.7 on 2018-08-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
